### ISSUE TITLE
Check linting of smart quotes and maiyamuk

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate-tooling#54]
In the Thai `.md` files, files are not being flagged that don't have spaces after a closing smart quote. Also there should be a space after the `ๆ` character unless it is the end of a line or before a final quote or parenthesis or bracket. I thought we made these filters already. However, I have been running into files where this is a problem.

**Comment by mattleff** [comment]
@bountonw Those rules are currently being applied to files in public folders. Do we want to move those up to apply to all stages?

**Comment by bountonw** [comment]
Yes.
