### ISSUE TITLE
ICML files missing “based on” yaml

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate-tooling#62]
@mattleff For PP, Some of the chapters have an additional subheading called “Based on”. This is in the yaml meta-data. This information needs to be included in the ICML files.

**Comment by mattleff** [comment]
@bountonw Should this be included as a heading and if so what heading level?

**Comment by bountonw** [comment]
I think it should be the next heading that isn't being used. So either h3 or h4. Welcome back to Thailand!

**Comment by mattleff** [comment]
> Welcome back to Thailand!

Thanks! 🇹🇭🌧️😀 

I'll send the PR with based-on as h4 since we have some h3s in LBF Ch. 25/37.
